.TH "Animation" 3 "Mon May 5 2014" "Version 200" "Indigo Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Animation \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Animation\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAnimation\fP (float *original=nullptr, float finished=0, int milliseconds=-1)"
.br
.ti -1c
.RI "\fBAnimation\fP (\fBObject\fP *original, float x, float y, float z, int frames)"
.br
.ti -1c
.RI "\fB~Animation\fP (void)"
.br
.ti -1c
.RI "void \fBUpdate\fP (float time)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBID\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Animation::Animation (float *original = \fCnullptr\fP, floatfinished = \fC0\fP, intmilliseconds = \fC-1\fP)"

.SS "Animation::Animation (\fBObject\fP *original, floatx, floaty, floatz, intframes)"

.SS "Animation::~Animation (void)"

.SH "Member Function Documentation"
.PP 
.SS "void Animation::Update (floattime)"

.SH "Member Data Documentation"
.PP 
.SS "int Animation::ID"


.SH "Author"
.PP 
Generated automatically by Doxygen for Indigo Engine from the source code\&.
