.TH "Camera.cpp" 3 "Mon May 5 2014" "Version 200" "Indigo Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Camera.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Camera\&.h'\fP
.br
\fC#include 'Indigo\&.h'\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include 'GLFW/glfw3\&.h'\fP
.br
\fC#include 'glm/vec3\&.hpp'\fP
.br
\fC#include 'glm/gtx/transform\&.hpp'\fP
.br
\fC#include 'glm/gtc/matrix_transform\&.hpp'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Indigo Engine from the source code\&.
