.TH "Lighting" 3 "Mon May 5 2014" "Version 200" "Indigo Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Lighting \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Lighting\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLighting\fP (void)"
.br
.ti -1c
.RI "\fBLighting\fP (const \fBLighting\fP &arrangement)"
.br
.ti -1c
.RI "\fB~Lighting\fP (void)"
.br
.ti -1c
.RI "void \fBSet_Ambient\fP (float intensity)"
.br
.ti -1c
.RI "void \fBSet_Light\fP (float X, float Y, float Z, bool direction=false, float power=60\&.0, glm::vec3 light_color=glm::vec3(1\&.0, 1\&.0, 1\&.0))"
.br
.ti -1c
.RI "void \fBUpdate_Lights\fP (void) const "
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Lighting::Lighting (void)"

.SS "Lighting::Lighting (const \fBLighting\fP &arrangement)"

.SS "Lighting::~Lighting (void)"

.SH "Member Function Documentation"
.PP 
.SS "void Lighting::Set_Ambient (floatintensity)"

.SS "void Lighting::Set_Light (floatX, floatY, floatZ, booldirection = \fCfalse\fP, floatpower = \fC60\&.0\fP, glm::vec3light_color = \fCglm::vec3(1\&.0,1\&.0,1\&.0)\fP)"

.SS "void Lighting::Update_Lights (void) const"


.SH "Author"
.PP 
Generated automatically by Doxygen for Indigo Engine from the source code\&.
