.TH "Lighting.h" 3 "Mon May 5 2014" "Version 200" "Indigo Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Lighting.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLighting\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Indigo Engine from the source code\&.
