.TH "Mesh" 3 "Mon May 5 2014" "Version 200" "Indigo Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mesh \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Mesh\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMesh\fP (void)"
.br
.ti -1c
.RI "\fBMesh\fP (const \fBMesh\fP &mesh)"
.br
.ti -1c
.RI "\fBMesh\fP (const char *filename, const char *texture=nullptr, const float shine=60\&.0, const glm::vec4 &color=glm::vec4(1, 1, 1, 1))"
.br
.ti -1c
.RI "\fB~Mesh\fP (void)"
.br
.ti -1c
.RI "void \fBInitialize\fP (const std::vector< glm::vec3 > &vertices, const std::vector< glm::vec2 > &uvs, const std::vector< glm::vec3 > &normals)"
.br
.ti -1c
.RI "glm::vec3 \fBFind_Flat_Normal\fP (const glm::vec3 &one, const glm::vec3 &two, const glm::vec3 &three) const "
.br
.ti -1c
.RI "void \fBUpdate_Hitbox\fP (glm::vec3 vertex)"
.br
.ti -1c
.RI "void \fBTexture\fP (const char *filename=nullptr)"
.br
.ti -1c
.RI "glm::vec2 \fBAuto_Texture_Coordinate\fP (const int index) const "
.br
.ti -1c
.RI "int \fBSize\fP (void) const "
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBMesh\fP \fBText\fP (const char *text, const float size=0\&.1, const char *font='Textures/Font\&.bmp', const glm::vec4 &color=glm::vec4(1, 1, 1, 1))"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "glm::vec3 \fBHitbox\fP [2]"
.br
.ti -1c
.RI "glm::vec4 \fBColor\fP"
.br
.ti -1c
.RI "float \fBShine\fP"
.br
.ti -1c
.RI "unsigned int \fBVertices_ID\fP"
.br
.ti -1c
.RI "unsigned int \fBElements_ID\fP"
.br
.ti -1c
.RI "unsigned int \fBNormals_ID\fP"
.br
.ti -1c
.RI "unsigned int \fBUV_ID\fP"
.br
.ti -1c
.RI "unsigned int \fBTexture_ID\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Mesh::Mesh (void)"

.SS "Mesh::Mesh (const \fBMesh\fP &mesh)"

.SS "Mesh::Mesh (const char *filename, const char *texture = \fCnullptr\fP, const floatshine = \fC60\&.0\fP, const glm::vec4 &color = \fCglm::vec4(1, 1, 1, 1)\fP)"

.SS "Mesh::~Mesh (void)"

.SH "Member Function Documentation"
.PP 
.SS "glm::vec2 Mesh::Auto_Texture_Coordinate (const intindex) const"

.SS "glm::vec3 Mesh::Find_Flat_Normal (const glm::vec3 &one, const glm::vec3 &two, const glm::vec3 &three) const"

.SS "void Mesh::Initialize (const std::vector< glm::vec3 > &vertices, const std::vector< glm::vec2 > &uvs, const std::vector< glm::vec3 > &normals)"

.SS "int Mesh::Size (void) const"

.SS "\fBMesh\fP Mesh::Text (const char *text, const floatsize = \fC0\&.1\fP, const char *font = \fC'Textures/Font\&.bmp'\fP, const glm::vec4 &color = \fCglm::vec4(1, 1, 1, 1)\fP)\fC [static]\fP"

.SS "void Mesh::Texture (const char *filename = \fCnullptr\fP)"

.SS "void Mesh::Update_Hitbox (glm::vec3vertex)"

.SH "Member Data Documentation"
.PP 
.SS "glm::vec4 Mesh::Color"

.SS "unsigned int Mesh::Elements_ID"

.SS "glm::vec3 Mesh::Hitbox[2]"

.SS "unsigned int Mesh::Normals_ID"

.SS "float Mesh::Shine"

.SS "unsigned int Mesh::Texture_ID"

.SS "unsigned int Mesh::UV_ID"

.SS "unsigned int Mesh::Vertices_ID"


.SH "Author"
.PP 
Generated automatically by Doxygen for Indigo Engine from the source code\&.
