.TH "Vertex_Compare" 3 "Mon May 5 2014" "Version 200" "Indigo Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Vertex_Compare \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator<\fP (const \fBVertex_Compare\fP &compare) const "
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "glm::vec3 \fBvertex\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "bool Vertex_Compare::operator< (const \fBVertex_Compare\fP &compare) const\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "glm::vec3 Vertex_Compare::vertex"


.SH "Author"
.PP 
Generated automatically by Doxygen for Indigo Engine from the source code\&.
