.TH "Direction.cpp" 3 "Mon May 5 2014" "Version 200" "Indigo Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Direction.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Direction\&.h'\fP
.br
\fC#include <iostream>\fP
.br
\fC#include 'glm/glm\&.hpp'\fP
.br
\fC#include 'glm/vec3\&.hpp'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Indigo Engine from the source code\&.
