.TH "Object.cpp" 3 "Mon May 5 2014" "Version 200" "Indigo Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Object.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'GL/glew\&.h'\fP
.br
\fC#include 'Object\&.h'\fP
.br
\fC#include 'Indigo\&.h'\fP
.br
\fC#include <iostream>\fP
.br
\fC#include 'GLFW/glfw3\&.h'\fP
.br
\fC#include 'glm/glm\&.hpp'\fP
.br
\fC#include 'glm/gtx/transform\&.hpp'\fP
.br
\fC#include 'glm/gtc/matrix_transform\&.hpp'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Indigo Engine from the source code\&.
