.TH "World.h" 3 "Mon May 5 2014" "Version 200" "Indigo Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
World.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Camera\&.h'\fP
.br
\fC#include 'Lighting\&.h'\fP
.br
\fC#include 'Object\&.h'\fP
.br
\fC#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBWorld\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Indigo Engine from the source code\&.
